#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)

# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import testlib


# Nondestructive tests all run in the same running VM. This allows them to run in Packit, Fedora, and
# RHEL dist-git gating. They must not permanently change any file or configuration on the system in a
# way that influences other tests.
@testlib.nondestructive
class TestApplication(testlib.MachineCase):
    def testBasic(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-cron")

        # verify the system/user level switcher, aligned to the right of the toolbar
        b.wait_text("#cron-level-system", "System")
        b.wait_attr_contains("#cron-level-system", "class", "pf-m-selected")
        b.wait_visible(".pf-v6-c-toolbar__item.pf-m-align-end")

        # add a root crontab and verify it shows up as a system level job
        m.execute("echo '0 0 * * * /usr/bin/uptime' | crontab -u root -")
        b.reload()
        b.wait_in_text(".pf-v6-c-data-list__item", "/usr/bin/uptime")

        # switch to user level jobs, which are empty for a fresh user
        b.click("#cron-level-user")
        b.wait_attr_contains("#cron-level-user", "class", "pf-m-selected")
        b.wait_text(".pf-v6-c-empty-state__body", "No user cron jobs")

        # the filter box is present; without jobs every filter shows the no match state
        b.set_input_text("#cron-jobs-filter", "nonexistent")
        b.wait_text(".pf-v6-c-empty-state__body", "No jobs match the filter")
        b.set_input_text("#cron-jobs-filter", "")
        b.wait_text(".pf-v6-c-empty-state__body", "No user cron jobs")

        # clean up the root crontab again
        m.execute("crontab -u root -r || true")

    def testAddJob(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-cron")

        # switch to the user level, where we can add a job without privileges
        b.click("#cron-level-user")
        b.wait_attr_contains("#cron-level-user", "class", "pf-m-selected")
        b.wait_text(".pf-v6-c-empty-state__body", "No user cron jobs")

        # open the add job dialog
        b.click("#cron-add-job")
        b.wait_visible("#cron-command")

        # pick a custom schedule and enter a command
        b.select_from_dropdown("#cron-schedule", "custom")
        b.set_input_text("#cron-schedule-custom", "0 4 * * 1")
        b.set_input_text("#cron-command", "/usr/bin/uptime")

        # the submit button becomes enabled once schedule and command are valid
        b.wait_attr("#cron-add-submit", "disabled", None)
        b.click("#cron-add-submit")

        # the new job shows up in the user level list and in the crontab
        b.wait_in_text(".pf-v6-c-data-list__item", "0 4 * * 1")
        b.wait_in_text(".pf-v6-c-data-list__item", "/usr/bin/uptime")

        # the dialog is closed after adding
        b.wait_not_present("#cron-command")

        output = m.execute("crontab -l")
        self.assertIn("0 4 * * 1 /usr/bin/uptime", output)

        # clean up the user crontab again
        m.execute("crontab -r || true")


if __name__ == '__main__':
    testlib.test_main()
